# Generated by Django 4.2.9 on 2024-01-17 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("domain_name", models.CharField(max_length=256)),
                ("from_date", models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0))),
                ("to_date", models.DateField(default=datetime.datetime.now)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "ordering": ("-created_at", "domain_name"),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("index_name", models.SlugField(max_length=200, unique=True)),
                ("is_indexed", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("meilisearch_id", models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ("wayback_machine_url", models.URLField(db_index=True, max_length=512, unique=True)),
                ("original_url", models.URLField(max_length=256)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("unix_timestamp", models.CharField(max_length=32)),
                ("mimetype", models.CharField(max_length=256)),
                ("status_code", models.IntegerField()),
                ("digest", models.CharField(max_length=256)),
                ("length", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="projects.domain"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ("domain", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="domains", to="projects.project"
            ),
        ),
    ]
