# Generated by Django 4.2.9 on 2024-01-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("domain_name", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "ordering": ("-created_at", "domain_name"),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("domain_name", models.CharField(max_length=256)),
                ("project", models.CharField(max_length=256)),
                ("original_url", models.URLField(max_length=256)),
                ("wayback_machine_url", models.URLField(max_length=512)),
                ("title", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
                ("unix_timestamp", models.IntegerField()),
                ("raw", models.TextField()),
                ("text", models.TextField()),
                ("mimetype", models.CharField(max_length=256)),
                ("status_code", models.IntegerField()),
                ("digest", models.CharField(max_length=256)),
                ("length", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.domain")),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ("-created_at", "domain"),
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
    ]
