# Generated by Django 4.2.9 on 2024-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_page_unix_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="search_index_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="update_index_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
