# Generated by Django 4.2.9 on 2024-01-24 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_search_index_key_project_update_index_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="update_index_key",
        ),
    ]
