# Generated by Django 4.2.9 on 2024-01-24 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_update_index_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="search_index_key",
            new_name="index_search_key",
        ),
    ]
