# Generated by Django 4.2.9 on 2024-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_remove_project_is_indexed_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("no_index", "No Index"), ("in_progress", "In Progress"), ("indexed", "Indexed")],
                default="no_index",
                max_length=16,
            ),
        ),
    ]
