# Generated by Django 4.2.9 on 2024-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="status",
            field=models.CharField(
                choices=[("no_index", "No Index"), ("in_progress", "In Progress"), ("indexed", "Indexed")],
                default="no_index",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="original_url",
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="page",
            name="wayback_machine_url",
            field=models.URLField(db_index=True, max_length=1024),
        ),
    ]
