# Generated by Django 4.2.9 on 2024-04-24 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_domain_status_alter_page_original_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CdxQuery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=256)),
                ("from_date", models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0))),
                ("to_date", models.DateField(default=datetime.datetime.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CDX Query",
                "verbose_name_plural": "CDX Queries",
                "ordering": ("url", "-from_date", "-to_date"),
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ("wayback_machine_url", "-created_at"),
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.RemoveField(
            model_name="page",
            name="domain",
        ),
        migrations.AddField(
            model_name="page",
            name="raw_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="index_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="index_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="index_task_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("no_index", "No Index"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("indexed", "Indexed"),
                ],
                default="no_index",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
        migrations.AddField(
            model_name="cdxquery",
            name="pages",
            field=models.ManyToManyField(related_name="cdx_queries", to="projects.page"),
        ),
        migrations.AddField(
            model_name="cdxquery",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cdx_queries", to="projects.project"
            ),
        ),
    ]
