version: '3'

volumes:
  chrono_scraper_local_postgres_data: {}
  chrono_scraper_local_postgres_data_backups: {}
  chrono_scraper_local_meilisearch_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: chrono_scraper_local_django
    container_name: chrono_scraper_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: chrono_scraper_production_postgres
    container_name: chrono_scraper_local_postgres
    volumes:
      - chrono_scraper_local_postgres_data:/var/lib/postgresql/data
      - chrono_scraper_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  docs:
    image: chrono_scraper_local_docs
    container_name: chrono_scraper_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./chrono_scraper:/app/chrono_scraper:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:latest
    container_name: chrono_scraper_local_mailpit
    ports:
      - '8025:8025'

  redis:
    image: redis:6
    container_name: chrono_scraper_local_redis

  celeryworker:
    <<: *django
    image: chrono_scraper_local_celeryworker
    container_name: chrono_scraper_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: chrono_scraper_local_celerybeat
    container_name: chrono_scraper_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: chrono_scraper_local_flower
    container_name: chrono_scraper_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: chrono_scraper_local_node
    container_name: chrono_scraper_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: chrono_scraper_local_meilisearch
    env_file:
      - ./.envs/.local/.meilisearch
    volumes:
      - chrono_scraper_local_meilisearch_data:/meili_data
    ports:
      - '7700:7700'
