"""Add invitation tokens table

Revision ID: 0dab0c3dcd41
Revises: 3284d061258b
Create Date: 2025-08-20 09:45:38.635475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dab0c3dcd41'
down_revision: Union[str, None] = '3284d061258b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_content_backup')
    op.drop_table('migration_log')
    op.drop_constraint('cdx_resume_states_domain_id_fkey', 'cdx_resume_states', type_='foreignkey')
    op.create_foreign_key(None, 'cdx_resume_states', 'domains', ['domain_id'], ['id'])
    op.drop_constraint('content_extractions_page_id_fkey', 'content_extractions', type_='foreignkey')
    op.create_foreign_key(None, 'content_extractions', 'pages', ['page_id'], ['id'])
    op.drop_constraint('domains_project_id_fkey', 'domains', type_='foreignkey')
    op.create_foreign_key(None, 'domains', 'projects', ['project_id'], ['id'])
    op.drop_constraint('entity_mentions_page_id_fkey', 'entity_mentions', type_='foreignkey')
    op.create_foreign_key(None, 'entity_mentions', 'pages', ['page_id'], ['id'])
    op.drop_constraint('evidence_page_id_fkey', 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'pages', ['page_id'], ['id'])
    op.drop_constraint('extracted_entities_project_id_fkey', 'extracted_entities', type_='foreignkey')
    op.drop_constraint('extracted_entities_page_id_fkey', 'extracted_entities', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_entities', 'pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'extracted_entities', 'projects', ['project_id'], ['id'])
    op.drop_constraint('investigation_timelines_page_id_fkey', 'investigation_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'investigation_timelines', 'pages', ['page_id'], ['id'])
    op.drop_constraint('page_comparisons_baseline_page_id_fkey', 'page_comparisons', type_='foreignkey')
    op.drop_constraint('page_comparisons_target_page_id_fkey', 'page_comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'page_comparisons', 'pages', ['baseline_page_id'], ['id'])
    op.create_foreign_key(None, 'page_comparisons', 'pages', ['target_page_id'], ['id'])
    op.drop_index('idx_pages_extracted_text_exists', table_name='pages', postgresql_where='(extracted_text IS NOT NULL)')
    op.drop_index('idx_pages_extracted_text_fts', table_name='pages', postgresql_using='gin', postgresql_where='(extracted_text IS NOT NULL)')
    op.drop_constraint('pages_domain_id_fkey', 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'domains', ['domain_id'], ['id'])
    op.drop_constraint('project_shares_project_id_fkey', 'project_shares', type_='foreignkey')
    op.create_foreign_key(None, 'project_shares', 'projects', ['project_id'], ['id'])
    op.drop_constraint('public_search_configs_project_id_fkey', 'public_search_configs', type_='foreignkey')
    op.create_foreign_key(None, 'public_search_configs', 'projects', ['project_id'], ['id'])
    op.drop_constraint('scrape_pages_domain_id_fkey', 'scrape_pages', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_pages', 'domains', ['domain_id'], ['id'])
    op.drop_constraint('scrape_sessions_project_id_fkey', 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint('search_history_project_id_fkey', 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'projects', ['project_id'], ['id'])
    op.drop_constraint('starred_items_page_id_fkey', 'starred_items', type_='foreignkey')
    op.drop_constraint('starred_items_project_id_fkey', 'starred_items', type_='foreignkey')
    op.create_foreign_key(None, 'starred_items', 'pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'starred_items', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.create_foreign_key('starred_items_project_id_fkey', 'starred_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('starred_items_page_id_fkey', 'starred_items', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.create_foreign_key('search_history_project_id_fkey', 'search_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key('scrape_sessions_project_id_fkey', 'scrape_sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_pages', type_='foreignkey')
    op.create_foreign_key('scrape_pages_domain_id_fkey', 'scrape_pages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'public_search_configs', type_='foreignkey')
    op.create_foreign_key('public_search_configs_project_id_fkey', 'public_search_configs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_shares', type_='foreignkey')
    op.create_foreign_key('project_shares_project_id_fkey', 'project_shares', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key('pages_domain_id_fkey', 'pages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_pages_extracted_text_fts', 'pages', [sa.text("to_tsvector('english'::regconfig, extracted_text)")], unique=False, postgresql_using='gin', postgresql_where='(extracted_text IS NOT NULL)')
    op.create_index('idx_pages_extracted_text_exists', 'pages', ['id'], unique=False, postgresql_where='(extracted_text IS NOT NULL)')
    op.drop_constraint(None, 'page_comparisons', type_='foreignkey')
    op.drop_constraint(None, 'page_comparisons', type_='foreignkey')
    op.create_foreign_key('page_comparisons_target_page_id_fkey', 'page_comparisons', 'pages', ['target_page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('page_comparisons_baseline_page_id_fkey', 'page_comparisons', 'pages', ['baseline_page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'investigation_timelines', type_='foreignkey')
    op.create_foreign_key('investigation_timelines_page_id_fkey', 'investigation_timelines', 'pages', ['page_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'extracted_entities', type_='foreignkey')
    op.drop_constraint(None, 'extracted_entities', type_='foreignkey')
    op.create_foreign_key('extracted_entities_page_id_fkey', 'extracted_entities', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('extracted_entities_project_id_fkey', 'extracted_entities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key('evidence_page_id_fkey', 'evidence', 'pages', ['page_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'entity_mentions', type_='foreignkey')
    op.create_foreign_key('entity_mentions_page_id_fkey', 'entity_mentions', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.create_foreign_key('domains_project_id_fkey', 'domains', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'content_extractions', type_='foreignkey')
    op.create_foreign_key('content_extractions_page_id_fkey', 'content_extractions', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cdx_resume_states', type_='foreignkey')
    op.create_foreign_key('cdx_resume_states_domain_id_fkey', 'cdx_resume_states', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.create_table('migration_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migration_log_pkey')
    )
    op.create_table('pages_content_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_content', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###