"""Add page management fields for tagging and review

Revision ID: 1c077a3ea9a9
Revises: 4f8a997c785a
Create Date: 2025-08-15 06:44:36.280464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c077a3ea9a9'
down_revision: Union[str, None] = '4f8a997c785a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('review_status', sa.String(length=20), nullable=True, server_default='unreviewed'))
    op.add_column('pages', sa.Column('page_category', sa.String(length=20), nullable=True))
    op.add_column('pages', sa.Column('priority_level', sa.String(length=20), nullable=True, server_default='medium'))
    op.add_column('pages', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('quick_notes', sa.String(length=500), nullable=True))
    op.add_column('pages', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('pages', sa.Column('is_duplicate', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('pages', sa.Column('duplicate_of_page_id', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'pages', 'users', ['reviewed_by'], ['id'])
    
    # Update existing records with default values
    op.execute("UPDATE pages SET review_status = 'unreviewed' WHERE review_status IS NULL")
    op.execute("UPDATE pages SET priority_level = 'medium' WHERE priority_level IS NULL")
    op.execute("UPDATE pages SET is_duplicate = false WHERE is_duplicate IS NULL")
    op.execute("UPDATE pages SET tags = '[]'::json WHERE tags IS NULL")
    
    # Make non-nullable after setting defaults
    op.alter_column('pages', 'review_status', nullable=False)
    op.alter_column('pages', 'priority_level', nullable=False)
    op.alter_column('pages', 'is_duplicate', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'reviewed_at')
    op.drop_column('pages', 'reviewed_by')
    op.drop_column('pages', 'tags')
    op.drop_column('pages', 'duplicate_of_page_id')
    op.drop_column('pages', 'is_duplicate')
    op.drop_column('pages', 'quality_score')
    op.drop_column('pages', 'quick_notes')
    op.drop_column('pages', 'review_notes')
    op.drop_column('pages', 'priority_level')
    op.drop_column('pages', 'page_category')
    op.drop_column('pages', 'review_status')
    # ### end Alembic commands ###