"""Add missing fields to scrape_pages table

Revision ID: 4f8a997c785a
Revises: 3c24c112f93f
Create Date: 2025-08-15 05:46:31.073219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f8a997c785a'
down_revision: Union[str, None] = '3c24c112f93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdx_resume_states',
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('from_date', sa.String(length=8), nullable=True),
    sa.Column('to_date', sa.String(length=8), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('url_path', sa.String(length=500), nullable=True),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('total_results_found', sa.Integer(), nullable=False),
    sa.Column('total_results_processed', sa.Integer(), nullable=False),
    sa.Column('estimated_total_results', sa.Integer(), nullable=True),
    sa.Column('resume_key', sa.Text(), nullable=True),
    sa.Column('cdx_api_url', sa.String(length=500), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_monitoring_logs',
    sa.Column('archive_available', sa.Boolean(), nullable=True),
    sa.Column('archive_response_time', sa.Float(), nullable=True),
    sa.Column('archive_error', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('completed_urls', sa.Integer(), nullable=False),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('failed_urls', sa.Integer(), nullable=False),
    sa.Column('pages_per_minute', sa.Float(), nullable=True),
    sa.Column('avg_fetch_time', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('raw_monitoring_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_error_logs',
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('wayback_url', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('is_recoverable', sa.Boolean(), nullable=False),
    sa.Column('suggested_retry_delay', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_page_id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retry_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scrape_page_id'], ['scrape_pages.id'], ),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('ix_permissions_name', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.alter_column('domains', 'min_page_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('200'))
    op.alter_column('domains', 'page_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3000'))
    op.alter_column('domains', 'pending_pages',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('domains', 'duplicate_pages',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('domains', 'list_pages_filtered',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('domains_project_id_fkey', 'domains', type_='foreignkey')
    op.create_foreign_key(None, 'domains', 'projects', ['project_id'], ['id'])
    op.drop_constraint('extracted_entities_project_id_fkey', 'extracted_entities', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_entities', 'projects', ['project_id'], ['id'])
    op.drop_constraint('pages_domain_id_fkey', 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'domains', ['domain_id'], ['id'])
    op.alter_column('plans', 'price_monthly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('plans', 'concurrent_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('plans', 'api_access',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('plans', 'priority_support',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('plans', 'custom_extraction',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('plans_name_key', 'plans', type_='unique')
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.drop_constraint('project_shares_project_id_fkey', 'project_shares', type_='foreignkey')
    op.create_foreign_key(None, 'project_shares', 'projects', ['project_id'], ['id'])
    op.drop_constraint('public_search_configs_project_id_fkey', 'public_search_configs', type_='foreignkey')
    op.create_foreign_key(None, 'public_search_configs', 'projects', ['project_id'], ['id'])
    op.add_column('scrape_pages', sa.Column('unix_timestamp', sa.String(length=14), nullable=True))
    op.add_column('scrape_pages', sa.Column('status_code', sa.Integer(), nullable=False))
    op.add_column('scrape_pages', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('scrape_pages', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('scrape_pages', sa.Column('extracted_content', sa.Text(), nullable=True))
    op.add_column('scrape_pages', sa.Column('markdown_content', sa.Text(), nullable=True))
    op.add_column('scrape_pages', sa.Column('is_pdf', sa.Boolean(), nullable=False))
    op.add_column('scrape_pages', sa.Column('is_duplicate', sa.Boolean(), nullable=False))
    op.add_column('scrape_pages', sa.Column('is_list_page', sa.Boolean(), nullable=False))
    op.add_column('scrape_pages', sa.Column('domain_id', sa.Integer(), nullable=False))
    op.add_column('scrape_pages', sa.Column('scrape_session_id', sa.Integer(), nullable=True))
    op.add_column('scrape_pages', sa.Column('error_type', sa.String(length=100), nullable=True))
    op.add_column('scrape_pages', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('scrape_pages', sa.Column('fetch_time', sa.Float(), nullable=True))
    op.add_column('scrape_pages', sa.Column('extraction_time', sa.Float(), nullable=True))
    op.add_column('scrape_pages', sa.Column('total_processing_time', sa.Float(), nullable=True))
    op.add_column('scrape_pages', sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('scrape_pages', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scrape_pages', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('scrape_pages', 'original_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('scrape_pages', 'wayback_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('scrape_pages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scrape_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('scrape_pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_scrape_pages_digest_hash', table_name='scrape_pages')
    op.drop_index('ix_scrape_pages_original_url', table_name='scrape_pages')
    op.drop_index('ix_scrape_pages_status', table_name='scrape_pages')
    op.create_foreign_key(None, 'scrape_pages', 'domains', ['domain_id'], ['id'])
    op.create_foreign_key(None, 'scrape_pages', 'scrape_sessions', ['scrape_session_id'], ['id'])
    op.drop_constraint('scrape_sessions_project_id_fkey', 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint('search_history_project_id_fkey', 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'projects', ['project_id'], ['id'])
    op.drop_constraint('starred_items_project_id_fkey', 'starred_items', type_='foreignkey')
    op.create_foreign_key(None, 'starred_items', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.create_foreign_key('starred_items_project_id_fkey', 'starred_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.create_foreign_key('search_history_project_id_fkey', 'search_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key('scrape_sessions_project_id_fkey', 'scrape_sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_pages', type_='foreignkey')
    op.drop_constraint(None, 'scrape_pages', type_='foreignkey')
    op.create_index('ix_scrape_pages_status', 'scrape_pages', ['status'], unique=False)
    op.create_index('ix_scrape_pages_original_url', 'scrape_pages', ['original_url'], unique=False)
    op.create_index('ix_scrape_pages_digest_hash', 'scrape_pages', ['digest_hash'], unique=False)
    op.alter_column('scrape_pages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('scrape_pages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('scrape_pages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scrape_pages', 'wayback_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('scrape_pages', 'original_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('scrape_pages', 'completed_at')
    op.drop_column('scrape_pages', 'last_attempt_at')
    op.drop_column('scrape_pages', 'first_seen_at')
    op.drop_column('scrape_pages', 'total_processing_time')
    op.drop_column('scrape_pages', 'extraction_time')
    op.drop_column('scrape_pages', 'fetch_time')
    op.drop_column('scrape_pages', 'max_retries')
    op.drop_column('scrape_pages', 'error_type')
    op.drop_column('scrape_pages', 'scrape_session_id')
    op.drop_column('scrape_pages', 'domain_id')
    op.drop_column('scrape_pages', 'is_list_page')
    op.drop_column('scrape_pages', 'is_duplicate')
    op.drop_column('scrape_pages', 'is_pdf')
    op.drop_column('scrape_pages', 'markdown_content')
    op.drop_column('scrape_pages', 'extracted_content')
    op.drop_column('scrape_pages', 'extracted_text')
    op.drop_column('scrape_pages', 'title')
    op.drop_column('scrape_pages', 'status_code')
    op.drop_column('scrape_pages', 'unix_timestamp')
    op.drop_constraint(None, 'public_search_configs', type_='foreignkey')
    op.create_foreign_key('public_search_configs_project_id_fkey', 'public_search_configs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_shares', type_='foreignkey')
    op.create_foreign_key('project_shares_project_id_fkey', 'project_shares', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.create_unique_constraint('plans_name_key', 'plans', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'custom_extraction',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('plans', 'priority_support',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('plans', 'api_access',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('plans', 'concurrent_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('plans', 'price_monthly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key('pages_domain_id_fkey', 'pages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'extracted_entities', type_='foreignkey')
    op.create_foreign_key('extracted_entities_project_id_fkey', 'extracted_entities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.create_foreign_key('domains_project_id_fkey', 'domains', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('domains', 'list_pages_filtered',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('domains', 'duplicate_pages',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('domains', 'pending_pages',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('domains', 'page_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3000'))
    op.alter_column('domains', 'min_page_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('200'))
    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_system_role', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_permissions_role_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='role_permissions_pkey')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_roles_pkey')
    )
    op.drop_table('page_error_logs')
    op.drop_table('scrape_monitoring_logs')
    op.drop_table('cdx_resume_states')
    # ### end Alembic commands ###