"""Add comprehensive security features and 2FA support

Revision ID: 777e63cf31a3
Revises: 8uzlxf9x22sb
Create Date: 2025-08-24 16:16:39.493342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '777e63cf31a3'
down_revision: Union[str, None] = '8uzlxf9x22sb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_url', sa.String(length=2048), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('before_values', sa.JSON(), nullable=True),
    sa.Column('after_values', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('compliance_flags', sa.JSON(), nullable=True),
    sa.Column('sensitive_data_accessed', sa.Boolean(), nullable=False),
    sa.Column('gdpr_relevant', sa.Boolean(), nullable=False),
    sa.Column('sox_relevant', sa.Boolean(), nullable=False),
    sa.Column('hipaa_relevant', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('database_queries', sa.Integer(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser_info', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_resource', 'audit_logs', ['action', 'resource_type'], unique=False)
    op.create_index('ix_audit_logs_admin_created', 'audit_logs', ['admin_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_user_id'), 'audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_archived'), 'audit_logs', ['archived'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index('ix_audit_logs_category_severity', 'audit_logs', ['category', 'severity'], unique=False)
    op.create_index('ix_audit_logs_compliance', 'audit_logs', ['gdpr_relevant', 'sox_relevant', 'hipaa_relevant'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_gdpr_relevant'), 'audit_logs', ['gdpr_relevant'], unique=False)
    op.create_index(op.f('ix_audit_logs_hipaa_relevant'), 'audit_logs', ['hipaa_relevant'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index('ix_audit_logs_ip_created', 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_retention', 'audit_logs', ['retention_until', 'archived'], unique=False)
    op.create_index('ix_audit_logs_sensitive_data', 'audit_logs', ['sensitive_data_accessed', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_sensitive_data_accessed'), 'audit_logs', ['sensitive_data_accessed'], unique=False)
    op.create_index('ix_audit_logs_session_created', 'audit_logs', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_sox_relevant'), 'audit_logs', ['sox_relevant'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # Add security columns with proper default values
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('password_history', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_last_used', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mfa_email_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('mfa_email_code_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False, server_default=sa.text('5')))
    op.add_column('users', sa.Column('require_mfa_for_admin', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('risk_score', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('last_risk_assessment', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('data_retention_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gdpr_consent_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('privacy_settings', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_settings')
    op.drop_column('users', 'gdpr_consent_date')
    op.drop_column('users', 'data_retention_days')
    op.drop_column('users', 'last_risk_assessment')
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'require_mfa_for_admin')
    op.drop_column('users', 'max_concurrent_sessions')
    op.drop_column('users', 'mfa_email_code_expiry')
    op.drop_column('users', 'mfa_email_code')
    op.drop_column('users', 'mfa_last_used')
    op.drop_column('users', 'mfa_enabled_at')
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'password_history')
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'last_failed_login')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'locked_at')
    op.drop_column('users', 'is_locked')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sox_relevant'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_session_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sensitive_data_accessed'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_sensitive_data', table_name='audit_logs')
    op.drop_index('ix_audit_logs_retention', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_ip_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hipaa_relevant'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_gdpr_relevant'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_compliance', table_name='audit_logs')
    op.drop_index('ix_audit_logs_category_severity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_archived'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_admin_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###