"""Add performance indexes for N+1 query optimization

Revision ID: ce456b0160d8
Revises: 09f463aad106
Create Date: 2025-08-22 02:08:39.999462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce456b0160d8'
down_revision: Union[str, None] = '09f463aad106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meilisearch_keys_expires_at', table_name='meilisearch_keys')
    op.drop_index('ix_meilisearch_keys_is_active', table_name='meilisearch_keys')
    op.drop_index('ix_meilisearch_keys_key_type', table_name='meilisearch_keys')
    op.drop_index('ix_meilisearch_keys_project_id', table_name='meilisearch_keys')
    op.drop_table('meilisearch_keys')
    op.drop_constraint('content_extractions_page_id_fkey', 'content_extractions', type_='foreignkey')
    op.create_foreign_key(None, 'content_extractions', 'pages', ['page_id'], ['id'])
    op.drop_constraint('domains_project_id_fkey', 'domains', type_='foreignkey')
    op.create_foreign_key(None, 'domains', 'projects', ['project_id'], ['id'])
    op.drop_constraint('entity_mentions_page_id_fkey', 'entity_mentions', type_='foreignkey')
    op.create_foreign_key(None, 'entity_mentions', 'pages', ['page_id'], ['id'])
    op.drop_constraint('extracted_entities_page_id_fkey', 'extracted_entities', type_='foreignkey')
    op.drop_constraint('extracted_entities_project_id_fkey', 'extracted_entities', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_entities', 'pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'extracted_entities', 'projects', ['project_id'], ['id'])
    op.drop_constraint('page_comparisons_baseline_page_id_fkey', 'page_comparisons', type_='foreignkey')
    op.drop_constraint('page_comparisons_target_page_id_fkey', 'page_comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'page_comparisons', 'pages', ['baseline_page_id'], ['id'])
    op.create_foreign_key(None, 'page_comparisons', 'pages', ['target_page_id'], ['id'])
    op.drop_constraint('pages_domain_id_fkey', 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'domains', ['domain_id'], ['id'])
    op.drop_constraint('project_shares_project_id_fkey', 'project_shares', type_='foreignkey')
    op.create_foreign_key(None, 'project_shares', 'projects', ['project_id'], ['id'])
    op.drop_constraint('public_search_configs_project_id_fkey', 'public_search_configs', type_='foreignkey')
    op.create_foreign_key(None, 'public_search_configs', 'projects', ['project_id'], ['id'])
    op.drop_constraint('scrape_pages_domain_id_fkey', 'scrape_pages', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_pages', 'domains', ['domain_id'], ['id'])
    op.drop_constraint('scrape_sessions_project_id_fkey', 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint('search_history_project_id_fkey', 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'projects', ['project_id'], ['id'])
    op.drop_constraint('starred_items_page_id_fkey', 'starred_items', type_='foreignkey')
    op.drop_constraint('starred_items_project_id_fkey', 'starred_items', type_='foreignkey')
    op.create_foreign_key(None, 'starred_items', 'pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'starred_items', 'projects', ['project_id'], ['id'])
    # Fix JSON conversion with proper casting
    op.execute("ALTER TABLE user_evaluations ALTER COLUMN red_flags TYPE JSON USING red_flags::json")
    op.execute("ALTER TABLE user_evaluations ALTER COLUMN positive_indicators TYPE JSON USING positive_indicators::json")
    
    # Performance indexes for N+1 query optimization
    # These indexes optimize the get_project_stats queries
    
    # Index for starred items (page_id and project_id lookups)
    op.execute("CREATE INDEX IF NOT EXISTS idx_starred_items_page_id ON starred_items(page_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_starred_items_project_id ON starred_items(project_id)")
    
    # Composite index for scrape_pages domain and status lookups
    op.execute("CREATE INDEX IF NOT EXISTS idx_scrape_pages_domain_id_status ON scrape_pages(domain_id, status)")
    
    # Index for domains by project
    op.execute("CREATE INDEX IF NOT EXISTS idx_domains_project_id ON domains(project_id)")
    
    # Index for pages by creation date (for recent queries)
    op.execute("CREATE INDEX IF NOT EXISTS idx_pages_created_at_desc ON pages(created_at DESC)")
    
    # Composite index for pages processed and indexed status
    op.execute("CREATE INDEX IF NOT EXISTS idx_pages_processed_indexed ON pages(processed, indexed) WHERE processed = true AND indexed = true")
    
    # Index for pages by scraped_at for last_scraped queries
    op.execute("CREATE INDEX IF NOT EXISTS idx_pages_scraped_at ON pages(scraped_at DESC)")
    
    # Index for pages by domain_id (for project stats queries)
    op.execute("CREATE INDEX IF NOT EXISTS idx_pages_domain_id ON pages(domain_id)")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop performance indexes
    op.execute("DROP INDEX IF EXISTS idx_pages_domain_id")
    op.execute("DROP INDEX IF EXISTS idx_pages_scraped_at")
    op.execute("DROP INDEX IF EXISTS idx_pages_processed_indexed")
    op.execute("DROP INDEX IF EXISTS idx_pages_created_at_desc")
    op.execute("DROP INDEX IF EXISTS idx_domains_project_id")
    op.execute("DROP INDEX IF EXISTS idx_scrape_pages_domain_id_status")
    op.execute("DROP INDEX IF EXISTS idx_starred_items_project_id")
    op.execute("DROP INDEX IF EXISTS idx_starred_items_page_id")
    
    # Revert JSON columns to TEXT
    op.execute("ALTER TABLE user_evaluations ALTER COLUMN positive_indicators TYPE TEXT")
    op.execute("ALTER TABLE user_evaluations ALTER COLUMN red_flags TYPE TEXT")
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.create_foreign_key('starred_items_project_id_fkey', 'starred_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('starred_items_page_id_fkey', 'starred_items', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.create_foreign_key('search_history_project_id_fkey', 'search_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key('scrape_sessions_project_id_fkey', 'scrape_sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_pages', type_='foreignkey')
    op.create_foreign_key('scrape_pages_domain_id_fkey', 'scrape_pages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'public_search_configs', type_='foreignkey')
    op.create_foreign_key('public_search_configs_project_id_fkey', 'public_search_configs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_shares', type_='foreignkey')
    op.create_foreign_key('project_shares_project_id_fkey', 'project_shares', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key('pages_domain_id_fkey', 'pages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'page_comparisons', type_='foreignkey')
    op.drop_constraint(None, 'page_comparisons', type_='foreignkey')
    op.create_foreign_key('page_comparisons_target_page_id_fkey', 'page_comparisons', 'pages', ['target_page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('page_comparisons_baseline_page_id_fkey', 'page_comparisons', 'pages', ['baseline_page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'extracted_entities', type_='foreignkey')
    op.drop_constraint(None, 'extracted_entities', type_='foreignkey')
    op.create_foreign_key('extracted_entities_project_id_fkey', 'extracted_entities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('extracted_entities_page_id_fkey', 'extracted_entities', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'entity_mentions', type_='foreignkey')
    op.create_foreign_key('entity_mentions_page_id_fkey', 'entity_mentions', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.create_foreign_key('domains_project_id_fkey', 'domains', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'content_extractions', type_='foreignkey')
    op.create_foreign_key('content_extractions_page_id_fkey', 'content_extractions', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.create_table('meilisearch_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_uid', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('key_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('key_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indexes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='meilisearch_keys_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meilisearch_keys_pkey'),
    sa.UniqueConstraint('key_uid', name='meilisearch_keys_key_uid_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_meilisearch_keys_project_id', 'meilisearch_keys', ['project_id'], unique=False)
    op.create_index('ix_meilisearch_keys_key_type', 'meilisearch_keys', ['key_type'], unique=False)
    op.create_index('ix_meilisearch_keys_is_active', 'meilisearch_keys', ['is_active'], unique=False)
    op.create_index('ix_meilisearch_keys_expires_at', 'meilisearch_keys', ['expires_at'], unique=False)
    # ### end Alembic commands ###