"""Add admin settings table for signup controls

Revision ID: d0304b16226e
Revises: c052773be04e
Create Date: 2025-08-23 14:07:18.057431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0304b16226e'
down_revision: Union[str, None] = 'c052773be04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cpr_page_id', table_name='cdx_page_registry')
    op.drop_index('idx_cpr_status', table_name='cdx_page_registry')
    op.drop_index('idx_cpr_url_time', table_name='cdx_page_registry')
    op.drop_table('cdx_page_registry')
    op.drop_index('idx_pp_domain', table_name='project_pages')
    op.drop_index('idx_pp_page', table_name='project_pages')
    op.drop_index('idx_pp_project', table_name='project_pages')
    op.drop_index('idx_pp_project_starred', table_name='project_pages')
    op.drop_index('idx_pp_review_status', table_name='project_pages')
    op.drop_table('project_pages')
    op.drop_index('idx_pages_v2_indexed', table_name='pages_v2')
    op.drop_index('idx_pages_v2_processed', table_name='pages_v2')
    op.drop_index('idx_pages_v2_timestamp', table_name='pages_v2')
    op.drop_index('idx_pages_v2_url', table_name='pages_v2')
    op.drop_index('idx_pages_v2_url_timestamp', table_name='pages_v2')
    op.drop_table('pages_v2')
    op.drop_index('ix_meilisearch_keys_expires_at', table_name='meilisearch_keys')
    op.drop_index('ix_meilisearch_keys_is_active', table_name='meilisearch_keys')
    op.drop_index('ix_meilisearch_keys_key_type', table_name='meilisearch_keys')
    op.drop_index('ix_meilisearch_keys_project_id', table_name='meilisearch_keys')
    op.drop_table('meilisearch_keys')
    op.drop_index('idx_domains_project_id', table_name='domains')
    op.drop_constraint('domains_project_id_fkey', 'domains', type_='foreignkey')
    op.create_foreign_key(None, 'domains', 'projects', ['project_id'], ['id'])
    op.drop_constraint('extracted_entities_project_id_fkey', 'extracted_entities', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_entities', 'projects', ['project_id'], ['id'])
    op.drop_index('idx_pages_created_at_desc', table_name='pages')
    op.drop_index('idx_pages_domain_id', table_name='pages')
    op.drop_index('idx_pages_processed_indexed', table_name='pages', postgresql_where='((processed = true) AND (indexed = true))')
    op.drop_index('idx_pages_scraped_at', table_name='pages')
    op.drop_constraint('pages_domain_id_fkey', 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'domains', ['domain_id'], ['id'])
    op.drop_constraint('project_shares_project_id_fkey', 'project_shares', type_='foreignkey')
    op.create_foreign_key(None, 'project_shares', 'projects', ['project_id'], ['id'])
    op.drop_constraint('public_search_configs_project_id_fkey', 'public_search_configs', type_='foreignkey')
    op.create_foreign_key(None, 'public_search_configs', 'projects', ['project_id'], ['id'])
    op.drop_index('idx_scrape_pages_domain_id_status', table_name='scrape_pages')
    op.drop_constraint('scrape_sessions_project_id_fkey', 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_sessions', 'projects', ['project_id'], ['id'])
    op.drop_constraint('search_history_project_id_fkey', 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'projects', ['project_id'], ['id'])
    op.drop_index('idx_starred_items_page_id', table_name='starred_items')
    op.drop_index('idx_starred_items_project_id', table_name='starred_items')
    op.drop_constraint('starred_items_project_id_fkey', 'starred_items', type_='foreignkey')
    op.drop_constraint('starred_items_page_id_fkey', 'starred_items', type_='foreignkey')
    op.create_foreign_key(None, 'starred_items', 'pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'starred_items', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.drop_constraint(None, 'starred_items', type_='foreignkey')
    op.create_foreign_key('starred_items_page_id_fkey', 'starred_items', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('starred_items_project_id_fkey', 'starred_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_starred_items_project_id', 'starred_items', ['project_id'], unique=False)
    op.create_index('idx_starred_items_page_id', 'starred_items', ['page_id'], unique=False)
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.create_foreign_key('search_history_project_id_fkey', 'search_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrape_sessions', type_='foreignkey')
    op.create_foreign_key('scrape_sessions_project_id_fkey', 'scrape_sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_scrape_pages_domain_id_status', 'scrape_pages', ['domain_id', 'status'], unique=False)
    op.drop_constraint(None, 'public_search_configs', type_='foreignkey')
    op.create_foreign_key('public_search_configs_project_id_fkey', 'public_search_configs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_shares', type_='foreignkey')
    op.create_foreign_key('project_shares_project_id_fkey', 'project_shares', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key('pages_domain_id_fkey', 'pages', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_pages_scraped_at', 'pages', [sa.text('scraped_at DESC')], unique=False)
    op.create_index('idx_pages_processed_indexed', 'pages', ['processed', 'indexed'], unique=False, postgresql_where='((processed = true) AND (indexed = true))')
    op.create_index('idx_pages_domain_id', 'pages', ['domain_id'], unique=False)
    op.create_index('idx_pages_created_at_desc', 'pages', [sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'extracted_entities', type_='foreignkey')
    op.create_foreign_key('extracted_entities_project_id_fkey', 'extracted_entities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.create_foreign_key('domains_project_id_fkey', 'domains', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_domains_project_id', 'domains', ['project_id'], unique=False)
    op.create_table('meilisearch_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_uid', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('key_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('key_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indexes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='meilisearch_keys_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='meilisearch_keys_pkey'),
    sa.UniqueConstraint('key_uid', name='meilisearch_keys_key_uid_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_meilisearch_keys_project_id', 'meilisearch_keys', ['project_id'], unique=False)
    op.create_index('ix_meilisearch_keys_key_type', 'meilisearch_keys', ['key_type'], unique=False)
    op.create_index('ix_meilisearch_keys_is_active', 'meilisearch_keys', ['is_active'], unique=False)
    op.create_index('ix_meilisearch_keys_expires_at', 'meilisearch_keys', ['expires_at'], unique=False)
    op.create_table('pages_v2',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unix_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('wayback_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('extracted_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('published_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capture_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('indexed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_retry_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pages_v2_pkey'),
    sa.UniqueConstraint('url', 'unix_timestamp', name='uq_pages_v2_url_timestamp', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_pages_v2_url_timestamp', 'pages_v2', ['url', 'unix_timestamp'], unique=False)
    op.create_index('idx_pages_v2_url', 'pages_v2', ['url'], unique=False)
    op.create_index('idx_pages_v2_timestamp', 'pages_v2', ['unix_timestamp'], unique=False)
    op.create_index('idx_pages_v2_processed', 'pages_v2', ['processed'], unique=False)
    op.create_index('idx_pages_v2_indexed', 'pages_v2', ['indexed'], unique=False)
    op.create_table('project_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('is_starred', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('page_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priority_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quick_notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_duplicate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('duplicate_of_page_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name='project_pages_added_by_fkey'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name='project_pages_domain_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages_v2.id'], name='project_pages_page_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_pages_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='project_pages_reviewed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pages_pkey'),
    sa.UniqueConstraint('project_id', 'page_id', name='uq_project_pages_project_page', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_pp_review_status', 'project_pages', ['review_status'], unique=False)
    op.create_index('idx_pp_project_starred', 'project_pages', ['project_id', 'is_starred'], unique=False)
    op.create_index('idx_pp_project', 'project_pages', ['project_id'], unique=False)
    op.create_index('idx_pp_page', 'project_pages', ['page_id'], unique=False)
    op.create_index('idx_pp_domain', 'project_pages', ['domain_id'], unique=False)
    op.create_table('cdx_page_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unix_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('scrape_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_by_project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_project_id'], ['projects.id'], name='cdx_page_registry_created_by_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages_v2.id'], name='cdx_page_registry_page_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cdx_page_registry_pkey'),
    sa.UniqueConstraint('url', 'unix_timestamp', name='uq_cdx_registry_url_timestamp', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_cpr_url_time', 'cdx_page_registry', ['url', 'unix_timestamp'], unique=False)
    op.create_index('idx_cpr_status', 'cdx_page_registry', ['scrape_status'], unique=False)
    op.create_index('idx_cpr_page_id', 'cdx_page_registry', ['page_id'], unique=False)
    # ### end Alembic commands ###