"""Create invitation_tokens table

Revision ID: d9e595226ce3
Revises: 0dab0c3dcd41
Create Date: 2025-08-20 09:57:25.141305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9e595226ce3'
down_revision: Union[str, None] = '0dab0c3dcd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_tokens',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('used_by_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_tokens_creator_user_id'), 'invitation_tokens', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_invitation_tokens_token'), 'invitation_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_tokens_token'), table_name='invitation_tokens')
    op.drop_index(op.f('ix_invitation_tokens_creator_user_id'), table_name='invitation_tokens')
    op.drop_table('invitation_tokens')
    # ### end Alembic commands ###