"""Add personal API keys and plan fields to user model

Revision ID: efb9d4a1be04
Revises: 8eb311d61986
Create Date: 2025-08-14 01:48:38.137494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb9d4a1be04'
down_revision: Union[str, None] = '8eb311d61986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('pages_per_month', sa.Integer(), nullable=False),
    sa.Column('projects_limit', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('api_access', sa.Boolean(), nullable=False),
    sa.Column('priority_support', sa.Boolean(), nullable=False),
    sa.Column('custom_extraction', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('cdx_resume_states',
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('from_date', sa.String(length=8), nullable=True),
    sa.Column('to_date', sa.String(length=8), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('url_path', sa.String(length=500), nullable=True),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('total_results_found', sa.Integer(), nullable=False),
    sa.Column('total_results_processed', sa.Integer(), nullable=False),
    sa.Column('estimated_total_results', sa.Integer(), nullable=True),
    sa.Column('resume_key', sa.Text(), nullable=True),
    sa.Column('cdx_api_url', sa.String(length=500), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_monitoring_logs',
    sa.Column('archive_available', sa.Boolean(), nullable=True),
    sa.Column('archive_response_time', sa.Float(), nullable=True),
    sa.Column('archive_error', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('completed_urls', sa.Integer(), nullable=False),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('failed_urls', sa.Integer(), nullable=False),
    sa.Column('pages_per_minute', sa.Float(), nullable=True),
    sa.Column('avg_fetch_time', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('raw_monitoring_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_pages',
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('wayback_url', sa.Text(), nullable=True),
    sa.Column('unix_timestamp', sa.String(length=14), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('digest_hash', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('is_pdf', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_list_page', sa.Boolean(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('fetch_time', sa.Float(), nullable=True),
    sa.Column('extraction_time', sa.Float(), nullable=True),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_error_logs',
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('wayback_url', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('is_recoverable', sa.Boolean(), nullable=False),
    sa.Column('suggested_retry_delay', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_page_id', sa.Integer(), nullable=False),
    sa.Column('scrape_session_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retry_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scrape_page_id'], ['scrape_pages.id'], ),
    sa.ForeignKeyConstraint(['scrape_session_id'], ['scrape_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('role_permissions')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.drop_table('user_roles')
    op.drop_index('ix_permissions_name', table_name='permissions')
    op.drop_table('permissions')
    op.add_column('domains', sa.Column('min_page_size', sa.Integer(), nullable=False))
    op.add_column('domains', sa.Column('page_size', sa.Integer(), nullable=False))
    op.add_column('domains', sa.Column('pending_pages', sa.Integer(), nullable=False))
    op.add_column('domains', sa.Column('duplicate_pages', sa.Integer(), nullable=False))
    op.add_column('domains', sa.Column('list_pages_filtered', sa.Integer(), nullable=False))
    op.add_column('domains', sa.Column('avg_fetch_time', sa.Float(), nullable=True))
    op.add_column('domains', sa.Column('success_rate', sa.Float(), nullable=True))
    op.add_column('domains', sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('openrouter_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('proxy_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('current_plan', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_plan')
    op.drop_column('users', 'proxy_api_key')
    op.drop_column('users', 'openrouter_api_key')
    op.drop_column('domains', 'estimated_completion')
    op.drop_column('domains', 'success_rate')
    op.drop_column('domains', 'avg_fetch_time')
    op.drop_column('domains', 'list_pages_filtered')
    op.drop_column('domains', 'duplicate_pages')
    op.drop_column('domains', 'pending_pages')
    op.drop_column('domains', 'page_size')
    op.drop_column('domains', 'min_page_size')
    op.create_table('permissions',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('permissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_roles_pkey')
    )
    op.create_table('roles',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_system_role', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_permissions_role_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='role_permissions_pkey')
    )
    op.drop_table('page_error_logs')
    op.drop_table('scrape_pages')
    op.drop_table('scrape_monitoring_logs')
    op.drop_table('cdx_resume_states')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###